###############################################################################.
# MODULE: download_data_btns_mod ---- 
# creates a menu button that when clicked on, provides 3 different options for downloading data (csv, rds or json)
# it then downloads the data in the format the user has selected
# note this can be used to download reactive data (i.e. data that is filtered in some way based on user selection) or
# non-reactive (i.e. data that you read into your global script that is not manipulated/filtered further based on user input)
# there is also an optional arguments in the server function to specify which columns of data to include in the download
# by default all columns are included unless you use pass a vector of column names to the selectedColumns argument
# note this module can be nested inside other modules where download buttons are required.


# UI function 
download_data_btns_ui <- function(id) {
  ns <- NS(id) # namespace
  shinyWidgets::dropdownButton(
    label = "Download data", icon = icon("download"), circle = FALSE, status = 'download', 
    tooltip = shinyWidgets::tooltipOptions(placement = "right", title = "Click to view available formats"),
    shiny::downloadLink(ns("downloadCSV"), label = "as CSV"),
    shiny::downloadLink(ns("downloadRDS"), label = "as RDS"),
    shiny::downloadLink(ns("downloadJSON"), label = "as JSON")
  )
}



# Server function 
download_data_btns_server <- function(id, data, selectedColumns = NULL) {
  moduleServer(id, function(input, output, session) {
    
    # check if data is reactive or not
    # check if any columns have been passed to the optional selectedColumns arg
    # if arg not used then all cols will be in the downloaded output
    getData <- function() {
      currentData <- if (is.reactive(data)) data() else data
      if (!is.null(selectedColumns)) {
        currentData[, selectedColumns, drop = FALSE]
      } else {
        currentData
      }
    }
    
    # download as csv
    output$downloadCSV <- downloadHandler(
      filename = paste0("scotpho_data_extract_", Sys.Date(), ".csv"),
      content = function(file) {
        write.csv(getData(), file, row.names = FALSE)
      }
    )
    
    # download as rds
    output$downloadRDS <- downloadHandler(
      filename = paste0("scotpho_data_extract_", Sys.Date(), ".rds"),
      content = function(file) {
        saveRDS(getData(), file)
      }
    )
    
    #download as json
    output$downloadJSON <- downloadHandler(
      filename = paste0("scotpho_data_extract_", Sys.Date(), ".json"),
      content = function(file) {
        jsonlite::write_json(as.list(getData()), file)
      }
      
    )
    
  })
}


##############################################################################
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################
# library(shiny)
# library(shinyWidgets)
# library(jsonlite)
# library(dplyr)
# 
# dummy_data <- data.frame(fruit = c("apples", "oranges", "pears"),
#                          colour = c("green", "orange", "green"))
# 
# 
# ui <- fluidPage(
#   h1("Download reactive data"),
#   selectInput(inputId = "colour_filter", label = "select fruit colour", choices = unique(dummy_data$colour)),
#   download_data_btns_ui("reactive_download"),
#   
#   h1("Download entire dataset"),
#   download_data_btns_ui("full_data_download")
#   )
# 
# server <- function(input, output, session) {
#   
#   
#   filtered_data <- reactive({
#     dummy_data |>
#       filter(colour == input$colour_filter)
#   })
#   
#   
#   download_data_btns_server("reactive_download", data = filtered_data)
#   download_data_btns_server("full_data_download", data = dummy_data)
# }
# 
# 
# shinyApp(ui, server)