###############################################################################.
# MODULE: tab_header_mod ---- 
#
# Used to create a header for the top of each profile tab, which contains information on the profile selected,
# as well as dynamic text detailing the selected areatype (e.g. Health boards) and areaname (e.g. NHS Borders )
# and a link that when clicked on, will expand the geography filters (which when changed will in turn update the dynamic text)
# it then returns the selected areaname and areatype as reactive values
# these reactive values can then be used within other modules/parts of the app (e.g. to filter data by selected geographies)
# note this module is passed to the header argument  of page_navbar so that it appears at the top of every single tab (conditional panels can be used to hide from specific tabs)
###############################################################################.

# ui function:
# id = unique id
tab_header_mod_ui <- function(id) {
  ns <- NS(id)
  
  areatype_list <- c("Alcohol & drug partnership", 
                     "Council area", 
                     "Health board",  
                     "HSC locality", 
                     "HSC partnership",  
                     "Intermediate zone",
                     "Scotland")
  
  tagList(
    # text detailing profile, area type and area name selected
    div(
      uiOutput(ns("profile_text")),
      uiOutput(ns("areatype_text")),
      uiOutput(ns("areaname_text"))
      ,
      # action link to expand geography filters (do we want to display as action link or actionButton?)
      actionLink(inputId = ns("show_geo_filters"), label = "Change area",icon = icon("filter")) |>
        bslib::tooltip("Click to change geography")
    ),
    # hidden filters to display when action link clicked
    shinyjs::hidden(
      tags$div(
        id = ns("geo_filters"), 
        layout_column_wrap(
          width = 1/2,
          selectInput(ns("areatype"), "Area type:", choices = areatype_list, selected = "Scotland"),
          layout_column_wrap(
            width = 1,
          selectInput(ns("areaname"), "Area name:", choices = "Scotland", selected = "Scotland"),
          # extra filter if Intermediate zone/locality selected (hidden by default)
          shinyjs::hidden(selectInput(ns("parent_area"), label = "First select a region for localities or intermediate zones", choices = partnership_name, width = "100%"))
          )
        ) 
      ) # close div
    )# close hidden function
  ) # close taglist
}


# server function:
# id = unique id which matches id assigned to ui fubction
# selected_profile = name of variable storing profile selection
tab_header_mod_server <- function(id, selected_profile) {
  moduleServer(id, function(input, output, session) {
    
    # toggle geography filters on and off when actionLink clicked
    shinyjs::onclick(id = "show_geo_filters", {
      shinyjs::toggle(id = "geo_filters")
    })
    
    # show/hide extra geography filter and
    # update choices for areaname based on areatype selection
    observeEvent(c(input$areatype, input$parent_area), {
      if (input$areatype %in% c("HSC locality", "Intermediate zone") && !is.null(input$parent_area)) {
        area_choices <- sort(geo_lookup$areaname[geo_lookup$areatype == input$areatype & geo_lookup$parent_area == input$parent_area])
        shinyjs::show("parent_area")
      } else {
      area_choices <- sort(geo_lookup$areaname[geo_lookup$areatype == input$areatype])
      shinyjs::hide("parent_area")
      }
      
      updateSelectInput(session, "areaname", choices = area_choices)
    })
    
    
    # dynamic text showing selected profile
    output$profile_text <- renderUI({
      tags$h1("Profile:", selected_profile(), class = "profile-header")
    })
    
 
    
    # dynamic text showing selected areatype
    output$areatype_text <- renderUI({
      tags$h2("Area type:", input$areatype,  class = "geography-header")
    })
    
    # dynamic text showing selected areaname
    output$areaname_text <- renderUI({
      tags$h2("Area name:", input$areaname,  class = "geography-header")
    })
    
    
    # Return the selected areatype and areaname
    # which can be used within other modules
    return(reactive({
      list(
        areatype = input$areatype,
        areaname = input$areaname
      )
    }))
    
  })
}


##############################################################################
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################
# library(bslib)
# library(shiny)
# library(shinyjs)
# 
# # dummy data
# main_dataset <- data.frame(areatype = c("Scotland", "Health board", "Health board", "Council area", "Council area",  "HSC partnership", "Intermediate zone", "Intermediate zone"),
#                            parent_area = c(NA, NA, NA, NA, NA, NA, "Aberdeen City", "Aberdeen City"),
#                            areaname = c("Scotland", "NHS Ayrshire & Arran", "NHS Borders", "Glasgow City", "Dumfries & Galloway", "Aberdeen City", "Culter", "Garthdee"))
# 
# # geography lookup
# geo_lookup <- unique(main_dataset)
# 
# 
# # HSC partnerships
# partnership_name <- sort(geo_lookup$areaname[geo_lookup$areatype=="HSC partnership"])
# 
# 
# # UI
# ui <- page_navbar(title = "Tab header module example",
#                   id = "main_navbar", # page_navbar id
#                   useShinyjs(), # required for filters to expand/collapse
#                   header = conditionalPanel(condition = "input.main_navbar !== 'P1'", tab_header_mod_ui(id = "my_dynamic_header")),
#                   nav_panel(title = "Profile 1 - do not display header", value = "P1"),
#                   nav_panel(title = "Profile 2", value = "P2"),
#                   nav_panel(title = "Profile 3", value = "P3")
# 
#                   )
# 
# 
# 
# server <- function(input, output, session) {
# 
# 
# #   reactive value to store profile (tab) selected
#   selected_profile <- reactiveVal()
# 
# 
#   # update reactive value storing profile (tab) when user switches tabs
#   observeEvent(input$main_navbar, {
#     selected_profile(input$main_navbar)
# 
#   })
# 
# 
#   # module to store geography selections and dynamically update header with selections
#   geo_selections <- tab_header_mod_server(id = "my_dynamic_header", selected_profile = selected_profile)
# 
# }
# 
# 
# shinyApp(ui, server)
# 



