###############################################################################.
# MODULE: button_mod ---- 
#
# Used to create buttons throughout the app which, when clicked, allow users to 
# navigate to another page in the tool
# The buttons will take 'profile name' and an icon (optional) which are supplied in main ui script.
# The location/set of the tab the button will take you to is linked to sections of code in the main ui script 
# Consistent naming of id and nav_id are essential for linking up buttons to tabs within the app
###############################################################################.


#module UI function -
#name is mandatory but icon is optional

button_modUI <- function(button_id, button_name, button_icon=NULL){
  ns <- shiny::NS(button_id)
  tagList(
    # custom js function to close the nav menu in the nav bar 1000 millisecs after button is clicked
    shinyjs::extendShinyjs(text = " shinyjs.closeNavMenu = function() {
        setTimeout(function() {$('.dropdown-menu').removeClass('show');}, 1000);}", functions = c("closeNavMenu")),
      shiny::actionButton(inputId= ns("button_nav"), 
                          label = button_name, 
                          class = "hero-button",
                          icon = button_icon))}


#module server function - 

button_modSERVER <- function(id, nav_id, parent_session) {
  shiny::moduleServer(id, function(input, output, session) {
    
    shiny::observeEvent(input$button_nav, {
      bslib::nav_select(id="nav",
                 selected = nav_id,
                 session = parent_session)
      
      shinyjs::js$closeNavMenu()})
  }) #close moduleServer
} #close server



###############################################################################.
# example usage - repex of how this module works can be generated by running
# the functions declared above then uncommenting the code below.
###############################################################################.

# library(bslib)
# library(shiny)
# library(shinyjs)
# 
# ui <- page_navbar(id = "nav",
#                   useShinyjs(),
#                   title = "Button card module example",
#                   nav_panel(title = "tab 1",
#                             value = "t1",
#                             p("Tab number 1"),
#                             button_modUI(button_id="go_to_tab2",
#                                          button_name="Tab 2",
#                                          button_icon = icon("otter"))),
#                   nav_panel(title = "tab 2",
#                             value = "t2",
#                             p("Tab number 2"))
#                   )
# 
# 
# server <- function(input, output, session) {
#   button_modSERVER(id = "go_to_tab2", nav_id="t2", parent_session=session)
# 
# }
# 
# shinyApp(ui, server)
# 
# 
