###############################################################################.
# MODULE: global_geography_filters_mod ---- 
#

# used to create a link that when clicked on, will expand the geography filters
# it then returns the selected areaname and areatype as reactive values
# these reactive values can then be used within other modules/parts of the app (e.g. to filter data by selected geographies)
# note this module is passed to the header argument  of page_navbar so that it appears at the top of every single tab (conditional panels can be used to hide from specific tabs - see example app below)
###############################################################################.

#ui function:
#id = unique id
global_geography_filters_ui <- function(id, areatype_choices, parent_area_choices) {
  ns <- NS(id)


  tagList(
    # link to show/hide geography filters when clicked on
    shiny::actionLink(inputId = ns("show_geo_filters"), label = "Change area", icon = icon("filter")) |>
      bslib::tooltip("Click to change geography"),

    # hidden filters to display when link clicked
    shinyjs::hidden(
      tags$div(
        id = ns("geo_filters"),
        layout_column_wrap(
          width = 1/2,
          selectInput(ns("areatype"), "Area type:", choices = areatype_choices, selected = "Scotland"),
          layout_column_wrap(
            width = 1,
            selectInput(ns("areaname"), "Area name:", choices = "Scotland", selected = "Scotland"),
            # extra filter if Intermediate zone/locality selected (hidden by default)
            shinyjs::hidden(selectInput(ns("parent_area"), label = "First select a region for localities or intermediate zones", choices = parent_area_choices, width = "100%"))
          )
        )
      ) # close div
    )# close hidden function
  ) # close taglist
}


# server function:
# id = unique id which matches id assigned to ui fubction
# selected_profile = name of variable storing profile selection
global_geography_filters_server <- function(id, geo_lookup) {
  moduleServer(id, function(input, output, session) {

    # toggle geography filters on and off when actionLink clicked
    shinyjs::onclick(id = "show_geo_filters", {
      shinyjs::toggle(id = "geo_filters")
    })

    # show/hide extra geography filter and
    # update choices for areaname based on areatype selection
    observeEvent(c(input$areatype, input$parent_area), {
      if (input$areatype %in% c("HSC locality", "Intermediate zone") && !is.null(input$parent_area)) {

        area_choices <- geo_lookup[areatype == input$areatype & parent_area == input$parent_area]$areaname
        shinyjs::show("parent_area")
      } else {
        area_choices <- geo_lookup[areatype == input$areatype]$areaname
        shinyjs::hide("parent_area")
      }

      updateSelectInput(session, "areaname", choices = area_choices)
    }, ignoreInit = TRUE)



    # Return the selected areatype and areaname
    # which can be used within other modules
    geo_selections <- eventReactive({
      input$areaname  # trigger only when areaname changes
    }, {
      list(
        areatype = isolate(input$areatype),
        areaname = input$areaname,
        parent_area = input$parent_area
      )
    })
    
    # Return the reactive values
    return(geo_selections)
    

  })
}





##############################################################################
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################
# library(bslib)
# library(shiny)
# library(shinyjs)
#library(data.table)
# 
# # dummy data
# main_dataset <- data.frame(areatype = c("Scotland", "Health board", "Health board", "Council area", "Council area",  "HSC partnership", "Intermediate zone", "Intermediate zone"),
#                            parent_area = c(NA, NA, NA, NA, NA, NA, "Aberdeen City", "Aberdeen City"),
#                            areaname = c("Scotland", "NHS Ayrshire & Arran", "NHS Borders", "Glasgow City", "Dumfries & Galloway", "Aberdeen City", "Culter", "Garthdee"))
# 
# # geography lookup
# geo_lookup <- unique(main_dataset)
# geo_lookup <- setDT(geo_lookup) # set to data.table format 
# 
# 
# # HSC partnerships
# partnership_names <- geo_lookup$areaname[geo_lookup$areatype=="HSC partnership"]
# 
# 
# # areatypes
# areatype_names <- unique(geo_lookup$areatype)
# 
# 
# # UI
# ui <- page_navbar(title = "Tab header module example",
#                   id = "main_navbar", # page_navbar id
#                   useShinyjs(), # required for filters to expand/collapse
#                   header = conditionalPanel(condition = "input.main_navbar !== 'Tab 1 - do not display header'", 
#                                             global_geography_filters_ui(id = "geo_filters", areatype_choices = areatype_names, parent_area_choices = partnership_names)
#                                             ),
#                   nav_panel(title = "Tab 1 - do not display header"),
#                   nav_panel(title = "Tab 2"),
#                   nav_panel(title = "Tab 3")
#                   )
# 
# 
# 
# server <- function(input, output, session) {
# 
# 
# #   reactive value to store profile (tab) selected
#   selected_tab <- reactiveVal()
# 
# 
#   # update reactive value storing profile (tab) when user switches tabs
#   observeEvent(input$main_navbar, {
#     selected_tab(input$main_navbar)
# 
#   })
# 
# 
#   # module to store geography selections 
#   geo_selections <- global_geography_filters_server(id = "geo_filters", geo_lookup = geo_lookup)
# 
# }
# 
# 
# shinyApp(ui, server)
# 
