### to do 
# - add an additional filter when IZ/locality selected - monica
# - decide whether to have actionLink or actionButton
# - formatting/style


###############################################################################.
# MODULE: tab_header_mod ---- 
#
# Used to create a header for the top of each profile tab, which contains information on the profile selected,
# as well as dynamic text detailing the selected areatype (e.g. Health boards) and areaname (e.g. NHS Borders )
# and a link that when clicked on, will expand the geography filters (which when changed will in turn update the dynamic text)
# these geography filters are synced, so when you include this module across multiple tabs, the filters will all update at once
# to avoid users having to re-select geographies each time they switch profile tab
# note for this synchronisation to work you must create 2 empty reactive value variables in the server script for the module to store/update the areatype and areaname
# these reactive values can then be used within other modules/parts of the app (e.g. to filter data by selected geographies)
###############################################################################.

# ui function:
# id = unique id
# profile_name = name of the profile i.e. "Health and Wellbeing"
tab_header_mod_ui <- function(id, profile_name) {
  ns <- NS(id)
  
  areatype_list <- c("Alcohol & drug partnership", 
                     "Council area", 
                     "Health board",  
                     "HSC locality", 
                     "HSC partnership",  
                     "Intermediate zone",
                     "Scotland")
  
  tagList(
    # text detailing profile, area type and area name selected
    tags$h1("Profile: ", profile_name),
    uiOutput(ns("areatype_text")),
    uiOutput(ns("areaname_text")),
    # action link to expand geography filters (do we want to display as action link or actionButton?)
    actionLink(inputId = ns("show_geo_filters"),
               label = "Change area",
               icon = icon("filter")
               ),
    # hidden filters to display when action link clicked
    shinyjs::hidden(
      tags$div(
      id = ns("geo_filters"),
      layout_column_wrap(
        selectInput(ns("areatype"), "Area type:", choices = areatype_list, selected = "Scotland"),
        selectInput(ns("areaname"), "Area name:", choices = "Scotland", selected = "Scotland")
      )
    ) # close div
  )# close hidden function
  ) # close taglist
}


# server function:
# id = unique id which matches id assigned to ui fubction
# selected_areatype = name of reactive created server to store selected areatype
# selected_areaname = name of the reactive value created in server to store selected areaname
tab_header_mod_server <- function(id, selected_areatype, selected_areaname) {
  moduleServer(id, function(input, output, session) {

    # show geography filters when action link clicked
    shinyjs::onclick(id = "show_geo_filters", {
      shinyjs::toggle(id = "geo_filters", anim = TRUE, animType = "slide")
    })


    # when user selects an areatype:
    # a. update reactive value which stores selected area type
    # b. update reactive value which stores selected area name to the first available areaname in the list for that particular areatype
    observeEvent(input$areatype, {
      selected_areatype(input$areatype)
      selected_areaname(unique(main_dataset$areaname[main_dataset$areatype == input$areatype])[1])
    })

    # when user selects an areaname:
    # update the reactive value which stores selected areaname
    # if statement needed here to avoid updating reactive value twice if was already updated in observe event above
    # otherwise arename dynamic text renders twice
    observeEvent(input$areaname, {
      if(input$areaname != selected_areaname()) {
        selected_areaname(input$areaname)
      }
    })

    # update what is selected from geography filters using reactive values
    observe({
      updateSelectInput(session, "areatype", selected = selected_areatype())

      available_areas <- unique(main_dataset$areaname[main_dataset$areatype == input$areatype])
      updateSelectInput(session, "areaname", choices = available_areas, selected = selected_areaname())
    })

    # dynamic text showing selected areatype
    output$areatype_text <- renderUI({
      tags$h2("Area type:", selected_areatype()
      )
    })

    # dynamic text showing selected areaname
    output$areaname_text <- renderUI({
      tags$h2("Area name:", selected_areaname()
      )
    })

  })
}


##############################################################################
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################
# library(bslib)
# library(shiny)
# library(shinyjs)
# 
# # dummy data
# main_dataset <- data.frame(areatype = c("Scotland", "Health board", "Health board", "Council area", "Council area"),
#                           areaname = c("Scotland", "NHS Ayrshire & Arran", "NHS Borders", "Glasgow City", "Dumfries & Galloway"))
# 
# ui <- page_navbar(title = "Tab header module example",
#                   useShinyjs(), # required for expanding/collapsing filters
#                   nav_panel(title = "Profile 1", 
#                             tab_header_mod_ui(id = "profile_1_header", profile_name = "Profile number 1")
#                             ),
#                   nav_panel(title = "Profile 2", 
#                             tab_header_mod_ui(id = "profile_2_header", profile_name = "Profile number 2")
#                             )
# )
# 
# 
# 
# server <- function(input, output, session) {
#   
#   # reactive values
#   my_selected_areatype <- reactiveVal()
#   my_selected_areaname <- reactiveVal()
#   
#   tab_header_mod_server(id = "profile_1_header", selected_areatype = my_selected_areatype, selected_areaname = my_selected_areaname)
#   tab_header_mod_server(id = "profile_2_header", selected_areatype = my_selected_areatype, selected_areaname = my_selected_areaname)
# }
# 
# 
# shinyApp(ui, server)
# 


