###############################################################################
#
# chart download module ---- 
#
###############################################################################

# This module creates a link that says 'save chart' that when clicked on, triggers some JS code to run 
# which downloads the chart displayed on the dashboard by using the 'exportChart' function from highcharts.
# This module can be nested within other modules (e.g. if creating cards which contains charts where you want to add download options)
# note if using within another module, make sure to wrap the chart_id in sessions$ns for it to work
# i.e. save_chart_mod_server("save_rank_chart", chart_id = session$ns("rank_chart))


# UI function:
# id = unique id
# see https://www.highcharts.com/docs/export-module/export-module-overview 
download_chart_mod_ui <- function(id) {
  ns <- NS(id)
  tagList(
    tags$script(
      HTML(
        "Shiny.addCustomMessageHandler('triggerDownload', function(message) {
      var chartIndex = Highcharts.charts.findIndex(function(chart) {
        return chart && chart.renderTo.id === message.chartId;
      });
        Highcharts.charts[chartIndex].exportChart({
          sourceWidth: message.width,
          sourceHeight: message.height
        });
    });"
      )
    ),
    actionLink(ns("chart_download"), label = "Save chart")
  )
}

# Server function:
# id = unique id
# chart_id = the inputId used for the chart displayed in the dashboard
download_chart_mod_server <- function(id, chart_id, width = 600, height = 400) {
  moduleServer(id, function(input, output, session) {
    
    
    
    # when button clicked, trigger the JS code to run
    observeEvent(input$chart_download, {
      session$sendCustomMessage("triggerDownload",
                                list(chartId = chart_id,
                                     width = width,
                                     height = height)
      )
    })
  })
}



##############################################################################
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################
# library(shiny)
# library(highcharter)
# 
# 
#  ui <- fluidPage(
# 
#  download_chart_mod_ui(id = "download_barchart"),
#   highchartOutput("my_chart")
#   )
# 
# server <- function(input, output, session){
# 
# 
#   output$my_chart <- renderHighchart({
#     hchart(mtcars$hp) |>
#       hc_chart(backgroundColor = 'white')
# 
#   })
# 
#   download_chart_mod_server(id = "download_barchart", chart_id = "my_chart")
# 
# 
# 
# }
# 
# shinyApp(ui, server)
# 
# 


