###############################################################################.
#
# chart download module ---- 
#
###############################################################################.

# This module creates a link that says 'save chart' that when clicked on, triggers some JS code to run 
# which downloads the chart displayed on the dashboard by using the 'exportChart' function from highcharts.
# see https://www.highcharts.com/docs/export-module/export-module-overview  for more details
# This module can be nested within other modules (e.g. if creating cards which contains charts where you want to add download options)
# note if using within another module, make sure to wrap the chart_id in ns for it to work
# i.e. save_chart_mod_server("save_rank_chart", chart_id = ns("rank_chart))


# UI function----
# id = unique id
download_chart_mod_ui <- function(id) {
  ns <- NS(id)
  tagList(
    tags$script(
      HTML(
        "Shiny.addCustomMessageHandler('triggerDownload', function(message) {
      var chartIndex = Highcharts.charts.findIndex(function(chart) {
        return chart && chart.renderTo.id === message.chartId;
      });
        Highcharts.charts[chartIndex].exportChart({
          sourceWidth: message.width,
          sourceHeight: message.height
        });
    });"
      )
    ),
    actionButton(ns("chart_download"), label = "Save chart (PNG)", class = "btn-sm me-2 btn-download", icon = icon("chart-simple"))
  )
}



# Server function----

# id = id matching the one assigned to ui function
# chart_id = the outputId of the chart
# width = optional argument to set width of the downloaded chart - set to 600 by default
# height = optional argument to set height of the downloaded chart - set to 400 by default
download_chart_mod_server <- function(id, chart_id, width = 600, height = 400) {
  moduleServer(id, function(input, output, session) {
    
    ns <- session$ns
    
    # when button clicked, trigger the JS code to run
    observeEvent(input$chart_download, {
      session$sendCustomMessage("triggerDownload",
                                list(chartId = chart_id,
                                     width = width,
                                     height = height)
      )
    })
  })
}



##############################################################################.
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################.
# library(shiny)
# library(highcharter)
# 
# 
# ui <- fluidPage(
#    download_chart_mod_ui(id = "download_barchart"),
#    highchartOutput(outputId = "my_chart")
#    )
# 
# server <- function(input, output, session){
# 
# 
#   output$my_chart <- renderHighchart({
#     hchart(mtcars$hp) |>
#       hc_chart(backgroundColor = 'white')
# 
#   })
# 
#   download_chart_mod_server(id = "download_barchart", chart_id = "my_chart")
# 
# 
# 
# }
# 
# shinyApp(ui, server)




