###############################################################################.
# MODULE: download_data_btns_mod ---- 
# creates a menu button that when clicked on, provides 3 different options for downloading data (csv, rds or json)
# it then downloads the data in the format the user has selected
# there is also an optional arguments in the server function to specify which columns of data to include in the download
# by default all columns are included unless you use pass a vector of column names to the selectedColumns argument
# note this module can be nested inside other modules where download buttons are required.


# UI function ----
# id = unique id 
# size = button size (can be 'sm', 'md' or 'lg')
download_data_btns_ui <- function(id, size = "sm") {
  ns <- NS(id) # namespace
  shinyWidgets::dropdownButton(
    label = "Download data", icon = icon("download"), circle = FALSE, status = 'download', size = size,
    shiny::downloadLink(ns("downloadCSV"), label = "as CSV"),
    shiny::downloadLink(ns("downloadRDS"), label = "as RDS"),
    shiny::downloadLink(ns("downloadJSON"), label = "as JSON"),
    shiny::downloadLink(ns("downloadParquet"), label = "as Parquet")
  )
}



# Server function ----
# id = unique id 
# data = name of data to download
# selectedColumns = vector of column names to include in data download (if required)
# file_name = name of downloaded file

download_data_btns_server <- function(id, data, selected_columns = NULL, file_name) {
  moduleServer(id, function(input, output, session) {
    
    dataset <- reactive({
      
      # Convert data.table to data.frame
      if ("data.table" %in% class(data())) {
        data <- as.data.frame(data())
      }
      
      
      # Select (and rename columns) if selected_columns arg is in use
      # otherwise download entire df
      if(!is.null(selected_columns)){
        data <- data |>
          select(all_of(selected_columns))
      } else {
      data
      }
    })
    
    # download as csv
    output$downloadCSV <- downloadHandler(
      filename = paste0(file_name, "_", Sys.Date(), ".csv"),
      content = function(file) {
        write.csv(as.data.frame(dataset()), file, row.names = FALSE)
      }
    )
    
    # download as rds
    output$downloadRDS <- downloadHandler(
      filename = paste0(file_name, "_", Sys.Date(), ".rds"),
      content = function(file) {
        saveRDS(dataset(), file)
      }
    )
    
    # download as json
    output$downloadJSON <- downloadHandler(
      filename = paste0(file_name, "_", Sys.Date(), ".json"),
      content = function(file) {
        jsonlite::write_json(as.list(dataset()), file)
      }
    )
    
    # download as parquet
    output$downloadParquet <- downloadHandler(
      filename = paste0(file_name, "_", Sys.Date(), ".parquet"),
      content = function(file) {
        nanoparquet::write_parquet(dataset(), file)
      }
    )
    
    
  })
}



##############################################################################.
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################.
# library(shiny)
# library(shinyWidgets)
# library(jsonlite)
# library(dplyr)
# 
# dummy_data <- data.frame(fruit = c("apples", "oranges", "pears"),
#                          colour = c("green", "orange", "green"))
# 
# 
# ui <- fluidPage(
#   h1("Download reactive data"),
#   selectInput(inputId = "colour_filter", label = "select fruit colour", choices = unique(dummy_data$colour)),
#   download_data_btns_ui("df_download"),
#   download_data_btns_ui("dt_download")
#   )
# 
# server <- function(input, output, session) {
# 
# 
#   df_data <- reactive({
#     dummy_data |>
#       filter(colour == input$colour_filter)
#   })
#   
#   
#   dt_data <- reactive({
#     dt <- setDT(dummy_data)
#     dt <- dt[colour == input$colour_filter]
#     dt
#   })
# 
# 
#   download_data_btns_server("dt_download", data = dt_data, selected_columns = c("fruit"))
#   download_data_btns_server("df_download", data = df_data)
# }
# 
# 
# shinyApp(ui, server)
