
###to do - need a fix to close the nav menu when navigates to a profile tab - monica

###############################################################################.
# MODULE: profile_homepage_btn_mod ---- 
#
# Used to create buttons (which are technically bslib cards) on the profiles tool homepage
# which, when clicked, allow users to navigate to a particular profile
# The buttons will take 'profile name' and an icon which are supplied in main ui script.
# The location/set of the tab the button will take you to is linked to sections of code in the main ui script 
# Consistent naming of id and nav_id are essential for linking up buttons to tabs within the app
###############################################################################.



# module ui function
# icon and description of the profile are optional arguments
profile_homepage_btn_modUI <- function(id, profile_icon = NULL, profile_name, description = NULL, class = NULL){
  ns <- NS(id)
  tagList(
    bslib::card(class = class,
      full_screen = FALSE,
      bslib::card_body(
        actionLink(inputId = ns("profile_nav"), style = "text-decoration: none; color: black;",
                   div(class = "d-flex flex-column align-items-center", 
                       div(icon(profile_icon, class = "fa-3x")),
                       br(),
                       h3(profile_name, style = "color: #3F3685; font-weight: 650; text-align:center;"),
                       p(description)))))
  )
}



# module server function
profile_homepage_btn_modSERVER <- function(id, profile_name, parent_session) {
  moduleServer(id, function(input, output, session) {
    
    #ns <- session$ns
    
    # when user clicks button: - 
    observeEvent(input$profile_nav, {
      
      # a. navigate to the profiles tab 
      bslib::nav_select(id = "nav", 
                        selected = "Profiles", 
                        session = parent_session)
      
      # b. update the profile filter
      updateSelectizeInput(inputId = "profile_choices", selected = profile_name, session = parent_session)

    })
  }) #close moduleServer
} # close server

##############################################################################.
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################.
# library(bslib)
# library(shiny)
# ui <- page_navbar(id = "nav",
#                   title = "Profile card module example",
#                   nav_panel(title = "tab 1",
#                             value = "t1",
#                             profile_homepage_btn_modUI(id = "go_to_tab2",
#                                                 profile_name = "Profile 2",
#                                                 profile_icon = "line-chart")
#                             ),
#                   nav_panel(title = "tab 2",
#                             value = "t2",
#                             p("Tab number 2"))
#                   )
# 
# 
# server <- function(input, output, session) {
#   profile_homepage_btn_modSERVER(id = "go_to_tab2", nav_id = "t2", parent_session = session)
# }
# 
# 
# shinyApp(ui, server)


